// <auto-generated />
using Investment_App.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Investment_App.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220102061809_inii")]
    partial class inii
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Investment_App.Model.FundDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentValueOfInvestedAmount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FundName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvestedAmount")
                        .HasColumnType("int");

                    b.Property<string>("InvestorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("FundDetails");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CurrentValueOfInvestedAmount = 0,
                            Description = "Nifty type fund",
                            FundName = "Nifty Cap Fund",
                            InvestedAmount = 0
                        },
                        new
                        {
                            ID = 2,
                            CurrentValueOfInvestedAmount = 0,
                            Description = "NiftyBank type fund",
                            FundName = "NiftyBank Cap Fund",
                            InvestedAmount = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
